service: book-worm

frameworkVersion: "2"

provider:
    name: aws
    runtime: go1.x
    lambdaHashingVersion: 20201221
    region: ap-south-1
    stage: prod

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:

# you can define service wide environment variables here
#  environment:
#    variable1: value1

#package:
#exclude:
#- ./**
#include:
#- ./bin/**

functions:
    book:
        handler: bin/book
        events:
            - http:
                  path: /book
                  method: get
                  cors: true
            - http:
                  path: /book/byProfile/{profileId}
                  method: get
                  cors: true
            - http:
                  path: /book/getAllById
                  method: get
                  cors: true
            - http:
                  path: /book/search
                  method: get
                  cors: true
            - http:
                  path: /book/{bookId}
                  method: get
                  cors: true
            - http:
                  path: /book
                  method: post
                  cors: true
            - http:
                  path: /book/uploadimage
                  method: post
                  cors: true
            - http:
                  path: /book/{bookId}
                  method: put
                  cors: true
            - http:
                  path: /book/{bookId}/editStatus
                  method: put
                  cors: true
            - http:
                  path: /book/{bookId}/editQuantity
                  method: put
                  cors: true
            - http:
                  path: /book/{bookId}
                  method: delete
                  cors: true
    order:
        handler: bin/order
        events:
            - http:
                  path: /order/getAllByProfile/{profileId}
                  method: get
                  cors: true
            - http:
                  path: /order/getAllWaiting/{profileId}
                  method: get
                  cors: true
            - http:
                  path: /order/{orderId}
                  method: get
                  cors: true
            - http:
                  path: /order
                  method: post
                  cors: true
            - http:
                  path: /order/{orderId}/updateStatus
                  method: put
                  cors: true
            - http:
                  path: /order/{orderId}
                  method: delete
                  cors: true
    profile:
        handler: bin/profile
        events:
            - http:
                  path: /profile/{profileId}
                  method: get
                  cors: true
            - http:
                  path: /profile/getByCognitoId/{cognitoId}
                  method: get
                  cors: true
            - http:
                  path: /profile
                  method: post
                  cors: true
            - http:
                  path: /profile/{profileId}
                  method: put
                  cors: true
            - http:
                  path: /profile/{profileId}/updateCart
                  method: put
                  cors: true
            - http:
                  path: /profile/{profileId}/updateProfileImage
                  method: put
            - http:
                  path: /profile/{profileId}
                  method: delete
                  cors: true
    review:
        handler: bin/review
        events:
            - http:
                  path: /review/getAllByBook/{bookId}
                  method: get
                  cors: true
            - http:
                  path: /review/{reviewId}
                  method: get
                  cors: true
            - http:
                  path: /review
                  method: post
                  cors: true
            - http:
                  path: /review/{reviewId}
                  method: put
                  cors: true
            - http:
                  path: /review/{reviewId}
                  method: delete
                  cors: true
